package ms3.service.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ms3.service.model.Assignment;

import ms3.service.service.AssignmentLocalServiceUtil;

/**
 * The extended model base implementation for the Assignment service. Represents a row in the &quot;train_Assignment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssignmentImpl}.
 * </p>
 *
 * @author jackt
 * @see AssignmentImpl
 * @see ms3.service.model.Assignment
 * @generated
 */
public abstract class AssignmentBaseImpl extends AssignmentModelImpl
    implements Assignment {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a assignment model instance should use the {@link Assignment} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AssignmentLocalServiceUtil.addAssignment(this);
        } else {
            AssignmentLocalServiceUtil.updateAssignment(this);
        }
    }
}
