package ms3.service.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ms3.service.model.Track;

import ms3.service.service.TrackLocalServiceUtil;

/**
 * The extended model base implementation for the Track service. Represents a row in the &quot;train_Track&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrackImpl}.
 * </p>
 *
 * @author jackt
 * @see TrackImpl
 * @see ms3.service.model.Track
 * @generated
 */
public abstract class TrackBaseImpl extends TrackModelImpl implements Track {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a track model instance should use the {@link Track} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TrackLocalServiceUtil.addTrack(this);
        } else {
            TrackLocalServiceUtil.updateTrack(this);
        }
    }
}
