package ms3.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TrackAssignment service. Represents a row in the &quot;train_TrackAssignment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ms3.service.model.impl.TrackAssignmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ms3.service.model.impl.TrackAssignmentImpl}.
 * </p>
 *
 * @author jackt
 * @see TrackAssignment
 * @see ms3.service.model.impl.TrackAssignmentImpl
 * @see ms3.service.model.impl.TrackAssignmentModelImpl
 * @generated
 */
public interface TrackAssignmentModel extends BaseModel<TrackAssignment> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a track assignment model instance should use the {@link TrackAssignment} interface instead.
     */

    /**
     * Returns the primary key of this track assignment.
     *
     * @return the primary key of this track assignment
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this track assignment.
     *
     * @param primaryKey the primary key of this track assignment
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the track assignment ID of this track assignment.
     *
     * @return the track assignment ID of this track assignment
     */
    public long getTrackAssignmentId();

    /**
     * Sets the track assignment ID of this track assignment.
     *
     * @param trackAssignmentId the track assignment ID of this track assignment
     */
    public void setTrackAssignmentId(long trackAssignmentId);

    /**
     * Returns the track ID of this track assignment.
     *
     * @return the track ID of this track assignment
     */
    public long getTrackId();

    /**
     * Sets the track ID of this track assignment.
     *
     * @param trackId the track ID of this track assignment
     */
    public void setTrackId(long trackId);

    /**
     * Returns the user screen name of this track assignment.
     *
     * @return the user screen name of this track assignment
     */
    @AutoEscape
    public String getUserScreenName();

    /**
     * Sets the user screen name of this track assignment.
     *
     * @param userScreenName the user screen name of this track assignment
     */
    public void setUserScreenName(String userScreenName);

    /**
     * Returns the assignment ID list of this track assignment.
     *
     * @return the assignment ID list of this track assignment
     */
    @AutoEscape
    public String getAssignmentIdList();

    /**
     * Sets the assignment ID list of this track assignment.
     *
     * @param assignmentIdList the assignment ID list of this track assignment
     */
    public void setAssignmentIdList(String assignmentIdList);

    /**
     * Returns the date assigned of this track assignment.
     *
     * @return the date assigned of this track assignment
     */
    @AutoEscape
    public String getDateAssigned();

    /**
     * Sets the date assigned of this track assignment.
     *
     * @param dateAssigned the date assigned of this track assignment
     */
    public void setDateAssigned(String dateAssigned);

    /**
     * Returns the admin of this track assignment.
     *
     * @return the admin of this track assignment
     */
    @AutoEscape
    public String getAdmin();

    /**
     * Sets the admin of this track assignment.
     *
     * @param admin the admin of this track assignment
     */
    public void setAdmin(String admin);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ms3.service.model.TrackAssignment trackAssignment);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ms3.service.model.TrackAssignment> toCacheModel();

    @Override
    public ms3.service.model.TrackAssignment toEscapedModel();

    @Override
    public ms3.service.model.TrackAssignment toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
